repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
        exclude: "^stream/old/.*"
    -   id: trailing-whitespace
        exclude: "^stream/old/.*"
    -   id: mixed-line-ending
        args: ['--fix=lf']
        exclude: "^stream/old/.*"
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff
      - id: ruff-format
